# clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secret-reloader-binding
subjects:
- kind: ServiceAccount
  name: {{ include "external-secrets-reloader.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }} # Namespace where your app runs
roleRef:
  kind: ClusterRole
  name: external-secret-reloader-editor-role
  apiGroup: rbac.authorization.k8s.io